version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_pathbit
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pathbit_challenge
    ports:
      - "5432:5432"
    volumes:
      - ./scripts/db:/docker-entrypoint-initdb.d

  api:
    build: .
    ports:
      - "5000:8080"  # Ajustado para porta padrão ASP.NET Core
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=pathbit_challenge;Username=postgres;Password=postgres
    depends_on:
      - postgres
